# Generated by Django 3.2.7 on 2021-10-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('condition', models.CharField(choices=[('N', 'New'), ('U', 'Used')], default='N', max_length=1)),
            ],
        ),
    ]
