# Generated by Django 3.2.7 on 2021-10-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorddb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='owned',
            field=models.BooleanField(default=False),
        ),
    ]
