# Generated by Django 3.2.7 on 2021-10-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorddb', '0002_record_owned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='condition',
            field=models.CharField(choices=[('N', 'New'), ('U', 'Used')], default='N', max_length=1, null=True),
        ),
    ]
