# Generated by Django 3.2.7 on 2021-10-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorddb', '0003_alter_record_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='condition',
            field=models.CharField(choices=[('', 'N/A'), ('N', 'New'), ('U', 'Used')], default='', max_length=1, null=True),
        ),
    ]
