# Generated by Django 3.2.7 on 2021-10-09 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recorddb', '0006_artist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
