# Generated by Django 3.2.7 on 2021-10-09 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recorddb', '0011_remove_record_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='artist_link',
        ),
        migrations.AddField(
            model_name='record',
            name='artist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recorddb.artist'),
            preserve_default=False,
        ),
    ]
