# Generated by Django 3.2.7 on 2021-10-09 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recorddb', '0007_delete_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='artist_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recorddb.artist'),
        ),
    ]
